import { Inventory } from './types';

export const inventoryData: Inventory[] = [
  {
    date: '2024-07-01',
    material: 'Cement',
    quantity: 1000,
    unit: 'bags',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '10 bags damaged',
    receivedBy: 'Jane Doe',
    _id: 'aA1bB2cC3dD4',
    activityType: 'Return'
  },
  {
    date: '2024-07-02',
    material: 'Blocks',
    quantity: 100,
    unit: 'pieces',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '5 blocks damaged',
    receivedBy: 'Jane Doe',
    _id: 'bB2cC3dD4eE5',
    activityType: 'Disburse'
  },
  {
    date: '2024-07-03',
    material: 'Sand',
    quantity: 7,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '2 trips damaged',
    receivedBy: 'Jane Doe',
    _id: 'cC3dD4eE5fF6',
    activityType: 'Disburse'
  },
  {
    date: '2024-07-04',
    material: 'Gravel',
    quantity: 10,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: 'all good',
    receivedBy: 'Jane Doe',
    _id: 'dD4eE5fF6gG7',
    activityType: 'Return'
  },
  {
    date: '2024-07-01',
    material: 'Cement',
    quantity: 1000,
    unit: 'bags',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '10 bags damaged',
    receivedBy: 'Jane Doe',
    _id: 'eE5fF6gG7hH8',
    activityType: 'Return'
  },
  {
    date: '2024-07-02',
    material: 'Blocks',
    quantity: 100,
    unit: 'pieces',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '5 blocks damaged',
    receivedBy: 'Jane Doe',
    _id: 'fF6gG7hH8iI9',
    activityType: 'Disburse'
  },
  {
    date: '2024-07-03',
    material: 'Sand',
    quantity: 7,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '2 trips damaged',
    receivedBy: 'Jane Doe',
    _id: 'gG7hH8iI9jJ0',
    activityType: 'Disburse'
  },
  {
    date: '2024-07-04',
    material: 'Gravel',
    quantity: 10,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: 'all good',
    receivedBy: 'Jane Doe',
    _id: 'hH8iI9jJ0kK1',
    activityType: 'Return'
  },
  {
    date: '2024-07-01',
    material: 'Cement',
    quantity: 1000,
    unit: 'bags',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '10 bags damaged',
    receivedBy: 'Jane Doe',
    _id: 'iI9jJ0kK1lL2',
    activityType: 'Disburse'
  },
  {
    date: '2024-07-02',
    material: 'Blocks',
    quantity: 100,
    unit: 'pieces',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '5 blocks damaged',
    receivedBy: 'Jane Doe',
    _id: 'jJ0kK1lL2mM3',
    activityType: 'Return'
  },
  {
    date: '2024-07-03',
    material: 'Sand',
    quantity: 7,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: '2 trips damaged',
    receivedBy: 'Jane Doe',
    _id: 'kK1lL2mM3nN4',
    activityType: 'Return'
  },
  {
    date: '2024-07-04',
    material: 'Gravel',
    quantity: 10,
    unit: 'trips',
    workArea: 'Construction',
    disbursedBy: 'John Doe',
    location: 'Site',
    notes: 'all good',
    receivedBy: 'Jane Doe',
    _id: 'lL2mM3nN4oO5',
    activityType: 'Disburse'
  }
];
